name: For each Kernel PR
on:
  pull_request:
    paths:
      - kernel/**
      - "!kernel/README.md"
jobs:
  kernel-validation:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use docker buildx
        run: docker buildx create --use

      - run: make -C kernel build ORG=quay.io/tinkerbell IMAGE=hook-kernel

    # TODO: add artifacts for the built images
    #- uses: actions/upload-artifact@v3
    #  with:
    #    name: TODO
    #    path: TODO
