name: For each Kernel PR
on:
  pull_request:
    paths:
      - kernel/**
      - "!kernel/README.md"
jobs:
  kernel-validation:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use docker buildx
        run: docker buildx create --use

      - run: make build_5.15.x
